name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true
    - name: Setup enviroment
      run: |
        sudo apt-get install bsdtar
        sudo gdebi devkitpro-pacman.deb
        sudo dkp-pacman --noconfirm -Syu
        sudo dkp-pacman --noconfirm -S devkitA64 switch-tools libnx switch-ffmpeg switch-glad switch-glfw switch-jansson switch-libdrm_nouveau switch-libexpat switch-libopus switch-libvpx switch-mbedtls switch-mesa switch-zlib switch-ffmpeg switch-pkg-config devkitpro-pkgbuild-helpers
    - name: Build libcurl 7.69.1-1
      run: |
        wget https://github.com/devkitPro/pacman-packages/raw/1582ad85914b14497fae32a9fe9074c0374f99f7/switch/curl/PKGBUILD
        dkp-makepkg
        sudo cp -r pkg/switch-curl/opt/devkitpro/portlibs/switch/* /opt/devkitpro/portlibs/switch
    - name: Build
      run: |
        export DEVKITPRO=/opt/devkitpro
        export DEVKITA64=/opt/devkitpro/devkitA64
        make -j NIGHTLY_BUILD=`git rev-parse --short "$GITHUB_SHA"`
    - name: Upload moonlight.nro
      uses: actions/upload-artifact@v1
      with:
        name: moonlight
        path: moonlight.nro
